source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'
gem 'rack-cors', :require => 'rack/cors'
gem 'pry'
gem 'geocoder'
gem 'figaro'
gem 'oauth'
gem 'jwt'
gem 'puma'
gem 'twitter'
